---
title: "第2章"
format: 
  html: 
    theme: journal
    highlight-style: pygments
    page-layout: article
number-sections: true
toc: true
toc-depth: 3
toc-location: left
code-fold: show
data: "最終更新: `r Sys.Date()`"
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, fig.align = "center", warning = FALSE)
library(magrittr)
library(ggplot2)
library(kableExtra)
library(modelsummary)
library(CausalInferenceTextbook)
color_main <- scales::viridis_pal(option = "D")(1)
```

# 無作為化実験

## \[2-1\] フィッシャーのp値

参照：[因果推論の計量経済学（川口、澤田）：第10章　差の差法とその周辺の発展的トピック](https://github.com/keisemi/EconometriciansGuide_CausalInference/blob/main/main/difference_in_differences_multiperiods.html)

パラメータの設定

```{r}
set.seed(1)
N <- 1000
R <- 1000
N_1 <- 500
```

母集団における平均処置効果`tau_population`の設定

```{r}
tau_polulation <- 0.2
```

```{r}
outcome_potential <- 
  tibble::tibble(
    y_0 = 
      rnorm(N,
            mean = 0,
            sd = 1),
    y_1 =
      rnorm(N,
            mean = tau_polulation,
            sd = 1)
  )

tau <- 
  outcome_potential %>% 
  dplyr::summarise(
    tau = mean(y_1 - y_0)
  ) %>% 
  dplyr::pull(tau)

outcome_potential %>% 
  head() %>% 
  kable() %>% 
  kable_styling()
```

```{r}
outcome_potential %>% 
  modelsummary::datasummary_skim()
```

```{r}
tau
```

```{r}
data_realized <- 
  generate_data_randomized(
    outcome_potential = outcome_potential,
    N_1 = N_1,
    seed = 1
  )

data_realized %>% 
  head() %>% 
  kbl() %>% 
  kable_styling()
```

```{r}
data_realized %>% 
  modelsummary::datasummary_skim()
```

```{r}
t <- 
  data_realized %>% 
  dplyr::summarise(
    t = mean(y * z) * 2 - mean(y * (1 - z)) * 2
  ) %>% 
  dplyr::pull(t)

t
```

```{r}
outcome_potential_null <- 
  data_realized %>% 
  dplyr::mutate(
    y_0 = y,
    y_1 = y
  )

t_distribution <- 
  1:R %>% 
  purrr::map(
    .,
    ~ generate_data_randomized(
        outcome_potential = outcome_potential_null,
        N_1 = N_1,
        seed = .
    ) %>% 
      calculate_difference_in_means()
  ) %>% 
  purrr::reduce(c)

pvalue <- 
  mean(
    abs(t_distribution) > abs(t)
  )

pvalue
```

```{r}
data.frame(
  statistics = abs(t_distribution)
) %>% 
  ggplot(
    aes(x = statistics)
  ) +
  geom_density() +
  geom_vline(xintercept = t, lty = 3, color = "blue") +
  theme_classic()
```

<br>

## \[2-2\]平均処置効果の推定 (平均の差)

```{r}
set.seed(1)
N <- 1000
R <- 1000
N_1 <- 500
```

平均処置効果`tau_populaiton`の設定。

```{r}
tau_population <- 0.2
```

```{r}
outcome_potential <- 
  tibble::tibble(
    y_0 = rnorm(
      N,
      mean = 0,
      sd = 1
    ),
    y_1 = rnorm(
      N,
      mean = tau_polulation,
      sd = 1
    )
  )

tau <- 
  outcome_potential %>% 
  dplyr::summarise(
    tau = mean(y_1 - y_0)
  ) %>% 
  dplyr::pull(tau)

outcome_potential %>% 
  head() %>% 
  kbl() %>% 
  kable_styling()
```

```{r}
outcome_potential %>% 
  modelsummary::datasummary_skim()
```

```{r}
tau
```

```{r}
data_realized <- 
  generate_data_randomized(
    outcome_potential = outcome_potential,
    N_1 = N_1,
    seed = 1
  )

data_realized %>% 
  head() %>% 
  kbl() %>% 
  kable_styling()
```

```{r}
data_realized %>% 
  modelsummary::datasummary_skim()
```

```{r}
mean_1 <- 
  data_realized %>% 
  dplyr::filter(
    z == 1
  ) %>% 
  dplyr::summarise(
    mean_1 = mean(y)
  ) %>% 
  dplyr::pull(mean_1)

mean_0 <- 
  data_realized %>% 
  dplyr::filter(
    z == 0
  ) %>% 
  dplyr::summarise(
    mean_0 = mean(y)
  ) %>% 
  dplyr::pull(mean_0)

tau_hat <- mean_1 - mean_0
tau_hat

n_1 <- 
  data_realized %>% 
  dplyr::filter(
    z == 1
  ) %>% 
  nrow()

n_0 <- 
  data_realized %>% 
  dplyr::filter(
    z == 0
  ) %>% 
  nrow()
```

```{r}
var_1 <- 
  data_realized %>% 
  dplyr::filter(
    z == 1
  ) %>% 
  dplyr::summarise(
    y = 
      sum(
        (y - mean_1)^2 / (n_1 - 1)
      )
  ) %>% 
  dplyr::pull(y)

var_0 <- 
  data_realized %>% 
  dplyr::filter(
    z == 0
  ) %>% 
  dplyr::summarise(
    y = sum(
      (y - mean_0)^2 / (n_0 - 1)
    ) 
  ) %>% 
  dplyr::pull(y)

var_hat <- 
  var_1 / n_1 +
  var_0 / n_0

var_hat
```

```{r}
se_hat <- sqrt(var_hat)
se_hat
```

```{r}
data.frame(
  tau_hat,
  se_hat,
  tau,
  tau_polulation
) %>% 
  magrittr::set_rownames(
    "Average Treatment Effect"
  ) %>% 
  kbl(col.names = c(
    "Estimate",
    "S.E.",
    "True(sample)",
    "True(population)"
    )
  ) %>% 
  kable_styling()
```

<br>

## \[2-3\]共変量の「統制」と回帰分析

```{r}
set.seed(1)
N <- 10000
N_1 <- 5000
```

母集団における平均処置効果`tau_population`の設定。

```{r}
tau_population <- 0.2
```

$Y_0^\ast(0) = \exp(x) - \exp(1/2)$

$\mathbb{E}\{Y_0^\ast(0)\} = 0$

```{r}
outcome_potential <- 
  tibble::tibble(
    x = rnorm(N),
    y_0 = rnorm(
      N,
      mean = exp(x) - exp(1/2),
      sd = 1
    ),
    y_1 = rnorm(
      N,
      tau_population,
      sd = 1
    )
  )

tau <- 
  outcome_potential %>% 
  dplyr::summarise(
    tau = mean(y_1 - y_0)
  ) %>% 
  dplyr::pull(tau)

outcome_potential %>% 
  head() %>% 
  kbl() %>% 
  kable_styling()
```

```{r}
outcome_potential %>% 
  modelsummary::datasummary_skim()
```

```{r}
tau
```

```{r}
data_realized <- 
  generate_data_randomized(
    outcome_potential = outcome_potential,
    N_1 = N_1,
    seed = 1
  )

data_realized %>% 
  head() %>% 
  kbl() %>% 
  kable_styling()
```

```{r}
data_realized %>% 
  modelsummary::datasummary_skim()
```

正しいモデルは 
$$
Y_i = Z_i\tau + (1 - Z_i)[\exp(X_i) - \exp(1/2)] + \epsilon_i
$$

$$
Y_i  = -\exp(1/2) + Z_i\tau + \dot{X}_i - Z_i\dot{X}_i + \epsilon_i
$$

```{r}
result_ols <- 
  c(
    "y ~ z",
    "y ~ z + x",
    "y ~ z + exp(x)",
    "y ~ z + x_dot + z:x_dot"
  ) %>% 
  purrr::map(as.formula) %>% 
  purrr::map(
    .,
    ~ lm(
      formula = .,
      data = 
        data_realized %>% 
        dplyr::mutate(
          x_dot = exp(x) - exp(1/2)
        )
    )
  )
```

```{r}
result_ols %>% 
  modelsummary(
    vcov = "HC2"
  )
```

```{r}
se_hetero <- 
  result_ols %>% 
  purrr::map(
    .,
    ~ data.frame(
      data_realized,
      residual = .$residuals,
      df = .$df.residual
    ) %>% 
      dplyr::mutate(
        z_bar = mean(z)
      ) %>% 
      dplyr::summarise(
        v = 
          sum(
            (z - z_bar)^2 * residual^2 /
              (z_bar * (1 - z_bar))^2
            )
        / (length(z) * mean(df))
        ) %>%
      dplyr::ungroup() %>% 
      sqrt()
    ) %>% 
  dplyr::bind_rows()
```

```{r}
data.frame(
  model = c("共変量なし", "線形共変量", "指数共変量", "正しい定式化"),
  "不均一分散頑健分散推定量" = se_hetero$v
) %>% 
 kbl() %>% 
  kable_styling()
```

<br>

## \[2-3\]共変量の「統制」と回帰分析

```{r}
set.seed(1)
N <- 2000
R <- 1000
q <- c(0.6, 0.4)
e <- c(0.3, 0.7)
N_1 <- N * q * e
```

母集団における平均処置効果`tau_polilation`

```{r}
tau_population <- c(0.2, 0.3)
```

```{r}
outcome_potential <- 
  1:2 %>% 
  purrr::map(
    function(g) {
      tibble::tibble(
        g = g,
        y_0 = 
          rnorm(N * q[g],
                mean = 0,
                sd = 0.1),
        y_1 = 
          rnorm(N * q[g],
                mean = tau_population[g],
                sd = 0.1)
      )
    }
  ) %>% 
  dplyr::bind_rows()

tau <- 
  outcome_potential %>%
  dplyr::group_by(g) %>% 
  dplyr::summarise(
    tau = mean(y_1 - y_0)
  ) %>% 
  dplyr::pull(tau)

outcome_potential %>% 
  head() %>% 
  kbl() %>% 
  kable_styling()
```

```{r}
outcome_potential %>% 
  modelsummary::datasummary_skim(fmt = 2)
```

```{r}
tau
```

```{r}
data_realized <- 
  generate_data_stratified(
    outcome_potential = outcome_potential,
    N_1 = N_1,
    seed = 1
  )

data_realized %>% 
  head() %>% 
  kbl() %>% 
  kable_styling()
```

```{r}
data_realized %>% 
  dplyr::filter(
    g == 1
  ) %>% 
  modelsummary::datasummary_skim()
```

```{r}
data_realized %>% 
  dplyr::filter(
    g == 2
  ) %>% 
  modelsummary::datasummary_skim()
```

各層に付与するウェイト`lambda`の定義 
$$
\lambda_g = q_ge_g(1 - e_g)
$$

```{r}
lambda <- 
  q * e * (1 - e)

t <- 
  data_realized %>% 
  dplyr::group_by(g) %>% 
  dplyr::reframe(
    y = (sum(y * z) / sum(z)) - 
      (sum(y * (1 - z)) / sum(1 - z)) 
  ) %>%
  dplyr::ungroup() %>% 
  dplyr::summarise(
    y = sum(y * lambda)
  ) %>% 
  dplyr::pull(y)
```

```{r}
outcome_potential_null <- 
  data_realized %>% 
  dplyr::mutate(
    y_0 = y,
    y_1 = y
  )

t_distribution <- 
  1:R %>% 
  purrr::map(
    .,
    ~ generate_data_stratified(
        outcome_potential = outcome_potential_null,
        N_1 = N_1,
        seed = .
    ) %>% 
      calculate_difference_in_means_stratified(
        data_realized = .,
        lambda = lambda
      )
  ) %>% 
  purrr::reduce(c)

pvalue <- 
  mean(
    abs(t_distribution) > abs(t)
  )

pvalue
```

```{r}
data.frame(
  statistics = abs(t_distribution)
  ) %>% 
  ggplot(aes(x = statistics)) +
  geom_density(
    color = color_main
    ) +
  geom_vline(
    xintercept = t,
    lty = 3, 
    color = color_main) +
  theme_classic()
```















































